# Generated by Django 5.2.15 on 2026-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_embed',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL 임베드'),
        ),
    ]
