# Generated by Django 5.2.15 on 2026-06-19 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_url_embed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='상세 내용')),
                ('level', models.CharField(choices=[('info', '일반 (파란색)'), ('warning', '주의 (노란색)'), ('danger', '긴급 (빨간색)'), ('success', '성공 (초록색)')], default='info', max_length=10, verbose_name='종류')),
                ('is_active', models.BooleanField(default=True, verbose_name='표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료일시 (비워두면 무기한)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-created_at'],
            },
        ),
    ]
