# Generated by Django 5.2.15 on 2026-06-22 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ai_credit_webdev'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiWebTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '실행 중'), ('done', '완료'), ('error', '오류'), ('cancelled', '취소')], default='running', max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('result_msg', models.TextField(blank=True)),
                ('error_msg', models.TextField(blank=True)),
                ('loop_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='blog.aiwebproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
