from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('search/', views.search_view, name='search'),
    path('search_old/<str:q>/', views.PostSearch.as_view(), name='search_old'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view(), name='update_comment'),
    path('update_post/<int:pk>/', views.PostUpdate.as_view(), name='update_post'),
    path('create_post/', views.PostCreate.as_view(), name='create_post'),
    path('tag/<str:slug>/', views.tag_page, name='tag'),
    path('category/<str:slug>/', views.category_page, name='category'),
    path('<int:pk>/new_comment/', views.new_comment, name='new_comment'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('series/', views.series_list, name='series_list'),
    path('series/create/', views.series_create, name='series_create'),
    path('series/my/', views.my_series, name='my_series'),
    path('series/<int:pk>/', views.series_detail, name='series_detail'),
    path('series/<int:pk>/edit/', views.series_edit, name='series_edit'),
    path('series/<int:pk>/delete/', views.SeriesDelete.as_view(), name='series_delete'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-delete-post/<int:pk>/', views.admin_delete_post, name='admin_delete_post'),
    path('backup-to-github/', views.backup_to_github, name='backup_to_github'),
    path('restore-from-github/', views.restore_from_github, name='restore_from_github'),
    path('spellcheck/', views.spellcheck_proxy, name='spellcheck'),
    path('notices/', views.notice_list_admin, name='notice_admin'),
    path('notices/<int:pk>/', views.notice_detail, name='notice_detail'),
    path('notices/create/', views.notice_create, name='notice_create'),
    path('notices/<int:pk>/edit/', views.notice_edit, name='notice_edit'),
    path('notices/<int:pk>/delete/', views.notice_delete, name='notice_delete'),

    # ── NEW FEATURES ──────────────────────────────────────────
    path('bookmark/<int:pk>/', views.bookmark_toggle, name='bookmark_toggle'),
    path('my-bookmarks/', views.my_bookmarks, name='my_bookmarks'),
    path('scheduled/', views.scheduled_posts, name='scheduled_posts'),
    path('<int:pk>/history/', views.post_history, name='post_history'),
    path('<int:pk>/history/<int:version_pk>/restore/', views.restore_post_version, name='restore_post_version'),
    path('comment/<int:pk>/like/', views.like_comment, name='like_comment'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/count/', views.notifications_count, name='notifications_count'),
    path('notifications/dropdown/', views.notifications_dropdown, name='notifications_dropdown'),
    path('popular-posts/', views.popular_posts_api, name='popular_posts_api'),
    path('darkmode/', views.darkmode_toggle, name='darkmode_toggle'),
    path('api/posts/', views.posts_api, name='posts_api'),
    path('api/autocomplete/', views.search_autocomplete, name='search_autocomplete'),
    path('ai-assist/', views.ai_writing_assist, name='ai_writing_assist'),
    path('comment/<int:pk>/like/', views.comment_like_toggle, name='comment_like_toggle'),
    path('api/popular/', views.popular_posts_api, name='popular_posts_api_v2'),
    path('api/darkmode/', views.darkmode_toggle, name='darkmode_toggle_v2'),
    path('<int:pk>/export-pdf/', views.export_post_pdf, name='export_post_pdf'),
    path('ai-assist/', views.ai_writing_assist, name='ai_writing_assist'),
    path('<int:pk>/pdf/', views.export_post_pdf, name='export_pdf'),
    path('my-dashboard/', views.my_dashboard, name='my_dashboard'),

    path('ai-chat/save/', views.ai_chat_save, name='ai_chat_save'),
    path('ai-chat/load/', views.ai_chat_load, name='ai_chat_load'),
    path('ai-chat/clear/', views.ai_chat_clear, name='ai_chat_clear'),

    path('', views.PostList.as_view(), name='index'),

    path('ai/credit/status/', views.ai_credit_status, name='ai_credit_status'),
    path('ai/credit/buy/', views.ai_credit_buy, name='ai_credit_buy'),
    path('ai/credit/shop/', views.ai_credit_shop, name='ai_credit_shop'),
    path('ai/chat/stream/', views.ai_chat_stream, name='ai_chat_stream'),
    path('admin-ai-credits/', views.admin_ai_credits, name='admin_ai_credits'),
    path('ai-webdev/', views.ai_webdev, name='ai_webdev'),
    path('ai-webdev/new/', views.ai_webdev_new_project, name='ai_webdev_new'),
    path('ai-webdev/<int:pk>/', views.ai_webdev_project, name='ai_webdev_project'),
    path('ai-webdev/<int:pk>/chat/', views.ai_webdev_chat, name='ai_webdev_chat'),
    path('ai-webdev/<int:pk>/upload/', views.ai_webdev_upload, name='ai_webdev_upload'),
    path('backup-status/', views.backup_status_api, name='backup_status_api'),
    path('ai-webdev/<int:pk>/tool/', views.ai_webdev_tool, name='ai_webdev_tool'),
    path('ai-webdev/<int:pk>/files/', views.ai_webdev_files, name='ai_webdev_files'),

    path('ai-webdev/<int:pk>/deploy/', views.ai_webdev_deploy, name='ai_webdev_deploy'),
    path('ai-webdev/<int:pk>/preview/', views.ai_webdev_preview, name='ai_webdev_preview'),
    path('ai-webdev/<int:pk>/preview/<path:filepath>', views.ai_webdev_static, name='ai_webdev_static'),
    path('ai-webdev/<int:pk>/terminal/', views.ai_webdev_terminal_stream, name='ai_webdev_terminal'),
    path('ai-webdev/<int:pk>/file/read/', views.ai_webdev_file_read, name='ai_webdev_file_read'),
    path('ai-webdev/<int:pk>/file/write/', views.ai_webdev_file_write, name='ai_webdev_file_write'),
    path('ai-webdev/<int:pk>/file/download/', views.ai_webdev_file_download, name='ai_webdev_file_download'),
    path('ai-webdev/<int:pk>/download-zip/', views.ai_webdev_zip_download, name='ai_webdev_zip_download'),
    path('ai-webdev/<int:pk>/history/', views.ai_webdev_history, name='ai_webdev_history'),
    path('ai-webdev/<int:pk>/task/status/', views.ai_webdev_task_status, name='ai_webdev_task_status'),
    path('ai-webdev/<int:pk>/task/upsert/', views.ai_webdev_task_upsert, name='ai_webdev_task_upsert'),
    path('ai-webdev/<int:pk>/proxy/<int:port>/', views.ai_webdev_proxy, name='ai_webdev_proxy', kwargs={'path': ''}),
    path('ai-webdev/<int:pk>/proxy/<int:port>/<path:path>', views.ai_webdev_proxy, name='ai_webdev_proxy_path'),
    path('ai-webdev/<int:pk>/clear-history/', views.ai_webdev_clear_history, name='ai_webdev_clear_history'),
    path('ai/credit/info/', views.ai_credit_info, name='ai_credit_info'),

    # ── 게시판 ──────────────────────────────────────
    path('boards/', views.board_list, name='board_list'),
    path('boards/<slug:slug>/', views.board_detail, name='board_detail'),
    path('boards/<slug:slug>/new/', views.board_post_create, name='board_post_create'),
    path('boards/<slug:board_slug>/posts/<int:pk>/', views.board_post_detail, name='board_post_detail'),
    path('boards/<slug:board_slug>/posts/<int:pk>/edit/', views.board_post_edit, name='board_post_edit'),
    path('boards/<slug:board_slug>/posts/<int:pk>/delete/', views.board_post_delete, name='board_post_delete'),
    path('boards/<slug:board_slug>/posts/<int:pk>/comment/', views.board_comment_create, name='board_comment_create'),
    path('boards/<slug:board_slug>/posts/<int:pk>/like/', views.board_post_like, name='board_post_like'),
    path('boards/comments/<int:comment_pk>/delete/', views.board_comment_delete, name='board_comment_delete'),
    path('boards/check-toxic/', views.board_check_toxic, name='board_check_toxic'),

    # ── 건의함 ──────────────────────────────────────
    path('suggestions/', views.suggestion_list, name='suggestion_list'),
    path('suggestions/new/', views.suggestion_create, name='suggestion_create'),
    path('suggestions/admin/', views.suggestion_admin_list, name='suggestion_admin_list'),
    path('suggestions/admin/<int:pk>/', views.suggestion_admin_detail, name='suggestion_admin_detail'),

    # ── Virtual OS ──────────────────────────────────────────────
    path('virtual-os/', views.virtual_os_index, name='virtual_os_index'),
    path('virtual-os/new/', views.virtual_os_session, name='virtual_os_new'),
    path('virtual-os/<int:pk>/', views.virtual_os_session, name='virtual_os_session'),
    path('virtual-os/<int:pk>/api/', views.virtual_os_api_session, name='virtual_os_api'),
    path('virtual-os/<int:pk>/save-state/', views.virtual_os_save_state, name='virtual_os_save_state'),
    path('virtual-os/<int:pk>/load-state/', views.virtual_os_load_state, name='virtual_os_load_state'),
    path('virtual-os/<int:pk>/save-vhd/', views.virtual_os_save_vhd, name='virtual_os_save_vhd'),
    path('virtual-os/<int:pk>/upload-iso/', views.virtual_os_upload_iso, name='virtual_os_upload_iso'),
    path('virtual-os/<int:pk>/iso/', views.virtual_os_stream_iso, name='virtual_os_stream_iso'),
    path('virtual-os/<int:pk>/delete/', views.virtual_os_delete_session, name='virtual_os_delete'),
]

    # ── AI 크레딧 & 스트리밍 & 웹개발 ─────────────────────────────
