from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('search/', views.search_view, name='search'),
    path('search_old/<str:q>/', views.PostSearch.as_view(), name='search_old'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view(), name='update_comment'),
    path('update_post/<int:pk>/', views.PostUpdate.as_view(), name='update_post'),
    path('create_post/', views.PostCreate.as_view(), name='create_post'),
    path('tag/<str:slug>/', views.tag_page, name='tag'),
    path('category/<str:slug>/', views.category_page, name='category'),
    path('<int:pk>/new_comment/', views.new_comment, name='new_comment'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('series/', views.series_list, name='series_list'),
    path('series/create/', views.series_create, name='series_create'),
    path('series/my/', views.my_series, name='my_series'),
    path('series/<int:pk>/', views.series_detail, name='series_detail'),
    path('series/<int:pk>/edit/', views.series_edit, name='series_edit'),
    path('series/<int:pk>/delete/', views.SeriesDelete.as_view(), name='series_delete'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-delete-post/<int:pk>/', views.admin_delete_post, name='admin_delete_post'),
    path('backup-to-github/', views.backup_to_github, name='backup_to_github'),
    path('restore-from-github/', views.restore_from_github, name='restore_from_github'),
    path('spellcheck/', views.spellcheck_proxy, name='spellcheck'),
    path('notices/', views.notice_list_admin, name='notice_admin'),
    path('notices/create/', views.notice_create, name='notice_create'),
    path('notices/<int:pk>/edit/', views.notice_edit, name='notice_edit'),
    path('notices/<int:pk>/delete/', views.notice_delete, name='notice_delete'),

    # ── NEW FEATURES ──────────────────────────────────────────
    path('bookmark/<int:pk>/', views.bookmark_toggle, name='bookmark_toggle'),
    path('my-bookmarks/', views.my_bookmarks, name='my_bookmarks'),
    path('scheduled/', views.scheduled_posts, name='scheduled_posts'),
    path('<int:pk>/history/', views.post_history, name='post_history'),
    path('<int:pk>/history/<int:version_pk>/restore/', views.restore_post_version, name='restore_post_version'),
    path('comment/<int:pk>/like/', views.like_comment, name='like_comment'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/count/', views.notifications_count, name='notifications_count'),
    path('notifications/dropdown/', views.notifications_dropdown, name='notifications_dropdown'),
    path('popular-posts/', views.popular_posts_api, name='popular_posts_api'),
    path('darkmode/', views.darkmode_toggle, name='darkmode_toggle'),
    path('api/posts/', views.posts_api, name='posts_api'),
    path('api/autocomplete/', views.search_autocomplete, name='search_autocomplete'),
    path('ai-assist/', views.ai_writing_assist, name='ai_writing_assist'),
    path('comment/<int:pk>/like/', views.comment_like_toggle, name='comment_like_toggle'),
    path('api/popular/', views.popular_posts_api, name='popular_posts_api_v2'),
    path('api/darkmode/', views.darkmode_toggle, name='darkmode_toggle_v2'),
    path('<int:pk>/export-pdf/', views.export_post_pdf, name='export_post_pdf'),
    path('ai-assist/', views.ai_writing_assist, name='ai_writing_assist'),
    path('<int:pk>/pdf/', views.export_post_pdf, name='export_pdf'),
    path('my-dashboard/', views.my_dashboard, name='my_dashboard'),

    path('ai-chat/save/', views.ai_chat_save, name='ai_chat_save'),
    path('ai-chat/load/', views.ai_chat_load, name='ai_chat_load'),
    path('ai-chat/clear/', views.ai_chat_clear, name='ai_chat_clear'),

    path('', views.PostList.as_view(), name='index'),
]
